version: '3.4'
services:
  db:
    container_name: database
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    expose:
      - 27017
    environment:
      MONGO_INITDB_DATABASE: notes-manager
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./mongo_data:/data/db


  redis:
    image: redis:alpine
    command: [ "redis-server", "--appendonly", "yes" ]
    deploy:
      replicas: 1
    volumes:
      - ./redis_data:/data
    ports:
      - "6379:6379"