version: '3.4'
services:
  db:
    container_name: database
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    expose:
      - 27017
    environment:
      MONGO_INITDB_DATABASE: notes-manager
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./mongo_data:/data/db